### PR TITLE
Add fast-blurhash to bench

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
https://calckey.social/notes/9h1dwe3kamb2668a

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
I'm not sure how to get `fast-blurhash` from unpkg...

image

**Comment by tamaina** [comment]
🚀🚀🚀

**Comment by tamaina** [comment]
image

STRANGE: fast-blurhash is slower than blurhash.

**Comment by tamaina** [comment]
image

In Chrome, fast-blurhash is faster but buraha is fastest.

**Comment by tamaina** [comment]
Safari 17, M1Pro

image

**Comment by tamaina** [comment]
Pixel 7

**Pull request merged**
